[package]
name = "wast_parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
wasmparser = "0.82.0"

[dev-dependencies]
wasm-tools = "1.0.1"